-- generated by pgadmin4

-- Table: public.available_deposits

-- DROP TABLE IF EXISTS public.available_deposits;

CREATE TABLE IF NOT EXISTS public.available_deposits
(
    deposit_id uuid NOT NULL,
    currency integer NOT NULL,
    deposit_period interval NOT NULL,
    deposit_sum money,
    deposit_percent numeric,
    deposit_type integer,
    CONSTRAINT available_deposits_pkey PRIMARY KEY (deposit_id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.available_deposits
    OWNER to postgres;
