-- generated by pgadmin4

-- Table: public.clients

-- DROP TABLE IF EXISTS public.clients;

CREATE TABLE IF NOT EXISTS public.clients
(
    client_id uuid NOT NULL,
    firstname character varying(100) COLLATE pg_catalog."default" NOT NULL,
    surname character varying(100) COLLATE pg_catalog."default" NOT NULL,
    document_number character varying(100) COLLATE pg_catalog."default" NOT NULL,
    document_type integer NOT NULL,
    document_date date NOT NULL,
    birth_date date NOT NULL,
    address character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT clients_pkey PRIMARY KEY (client_id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.clients
    OWNER to postgres;

COMMENT ON TABLE public.clients
    IS 'Клиенты';
