-- generated by pgadmin4

-- Table: public.contracts

-- DROP TABLE IF EXISTS public.contracts;

CREATE TABLE IF NOT EXISTS public.contracts
(
    contract_id uuid NOT NULL,
    amount money NOT NULL,
    starting_date timestamp with time zone NOT NULL,
    ending_date timestamp with time zone NOT NULL,
    client_id uuid NOT NULL,
    current_account_id uuid NOT NULL,
    deposit_account_id uuid NOT NULL,
    deposit_type uuid NOT NULL,
    CONSTRAINT contracts_pkey PRIMARY KEY (contract_id),
    CONSTRAINT "deposit_account_id one-to-one" UNIQUE (deposit_account_id),
    CONSTRAINT contracts_client_id_fkey FOREIGN KEY (client_id)
        REFERENCES public.clients (client_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID,
    CONSTRAINT contracts_client_id_fkey1 FOREIGN KEY (client_id)
        REFERENCES public.clients (client_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID,
    CONSTRAINT contracts_client_id_fkey2 FOREIGN KEY (client_id)
        REFERENCES public.clients (client_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID,
    CONSTRAINT contracts_current_account_id_fkey FOREIGN KEY (current_account_id)
        REFERENCES public.current_accounts (account_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID,
    CONSTRAINT contracts_current_account_id_fkey1 FOREIGN KEY (current_account_id)
        REFERENCES public.current_accounts (account_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID,
    CONSTRAINT contracts_current_account_id_fkey2 FOREIGN KEY (current_account_id)
        REFERENCES public.current_accounts (account_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID,
    CONSTRAINT contracts_deposit_account_id_fkey FOREIGN KEY (deposit_account_id)
        REFERENCES public.deposit_accounts (deposit_account_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID,
    CONSTRAINT contracts_deposit_account_id_fkey1 FOREIGN KEY (deposit_account_id)
        REFERENCES public.deposit_accounts (deposit_account_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID,
    CONSTRAINT contracts_deposit_account_id_fkey2 FOREIGN KEY (deposit_account_id)
        REFERENCES public.deposit_accounts (deposit_account_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID,
    CONSTRAINT contracts_deposit_type_fkey FOREIGN KEY (deposit_type)
        REFERENCES public.available_deposits (deposit_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID,
    CONSTRAINT contracts_deposit_type_fkey1 FOREIGN KEY (deposit_type)
        REFERENCES public.available_deposits (deposit_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID,
    CONSTRAINT contracts_deposit_type_fkey2 FOREIGN KEY (deposit_type)
        REFERENCES public.available_deposits (deposit_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.contracts
    OWNER to postgres;
