-- generated by pgadmin4

-- Table: public.deposit_accounts

-- DROP TABLE IF EXISTS public.deposit_accounts;

CREATE TABLE IF NOT EXISTS public.deposit_accounts
(
    deposit_account_id uuid NOT NULL,
    currency integer NOT NULL,
    stating_date timestamp with time zone NOT NULL,
    created_by uuid NOT NULL,
    CONSTRAINT one_to_one PRIMARY KEY (deposit_account_id),
    CONSTRAINT deposit_accounts_created_by_fkey FOREIGN KEY (created_by)
        REFERENCES public.clients (client_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID,
    CONSTRAINT deposit_accounts_created_by_fkey1 FOREIGN KEY (created_by)
        REFERENCES public.clients (client_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID,
    CONSTRAINT deposit_accounts_created_by_fkey2 FOREIGN KEY (created_by)
        REFERENCES public.clients (client_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.deposit_accounts
    OWNER to postgres;
