-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.clients
(
    client_id uuid NOT NULL,
    name text NOT NULL,
    surname text NOT NULL,
    document_number bigint NOT NULL,
    document_type integer NOT NULL,
    document_date date NOT NULL,
    birth_date date NOT NULL,
    address text NOT NULL,
    PRIMARY KEY (client_id)
);

COMMENT ON TABLE public.clients
    IS 'Клиенты';

CREATE TABLE IF NOT EXISTS public.deposit_accounts
(
    deposit_account_id uuid NOT NULL,
    currency integer NOT NULL,
    stating_date date NOT NULL,
    created_by uuid NOT NULL,
    PRIMARY KEY (deposit_account_id),
    CONSTRAINT one_to_one UNIQUE (deposit_account_id)
);

CREATE TABLE IF NOT EXISTS public.current_accounts
(
    account_id uuid NOT NULL,
    currency integer NOT NULL,
    starting_date date NOT NULL,
    created_by uuid NOT NULL,
    PRIMARY KEY (account_id)
);

CREATE TABLE IF NOT EXISTS public.contracts
(
    contract_id uuid NOT NULL,
    amount money NOT NULL,
    starting_date date NOT NULL,
    ending_date date NOT NULL,
    client_id uuid NOT NULL,
    current_account_id uuid NOT NULL,
    deposit_account_id uuid NOT NULL,
    deposit_type uuid NOT NULL,
    PRIMARY KEY (contract_id),
    CONSTRAINT "deposit_account_id one-to-one" UNIQUE (deposit_account_id)
);

CREATE TABLE IF NOT EXISTS public.available_deposits
(
    deposit_id uuid NOT NULL,
    currency integer NOT NULL,
    period interval NOT NULL,
    PRIMARY KEY (deposit_id)
);

ALTER TABLE IF EXISTS public.deposit_accounts
    ADD FOREIGN KEY (created_by)
    REFERENCES public.clients (client_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.current_accounts
    ADD FOREIGN KEY (created_by)
    REFERENCES public.clients (client_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.contracts
    ADD FOREIGN KEY (deposit_account_id)
    REFERENCES public.deposit_accounts (deposit_account_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.contracts
    ADD FOREIGN KEY (current_account_id)
    REFERENCES public.current_accounts (account_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.contracts
    ADD FOREIGN KEY (client_id)
    REFERENCES public.clients (client_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.contracts
    ADD FOREIGN KEY (deposit_type)
    REFERENCES public.available_deposits (deposit_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;